const FLAG_MAP: Record<string, string> = {
  // Americas
  "Brazil": "🇧🇷",
  "United States": "🇺🇸",
  "USA": "🇺🇸",
  "Canada": "🇨🇦",
  "Mexico": "🇲🇽",
  "Uruguay": "🇺🇾",
  "Argentina": "🇦🇷",
  "Colombia": "🇨🇴",
  "Venezuela": "🇻🇪",
  "Peru": "🇵🇪",
  "Chile": "🇨🇱",
  "Ecuador": "🇪🇨",
  "Bolivia": "🇧🇴",
  "Paraguay": "🇵🇾",
  "Panama": "🇵🇦",
  "Jamaica": "🇯🇲",
  "Cuba": "🇨🇺",
  "Trinidad and Tobago": "🇹🇹",
  "Guyana": "🇬🇾",
  // Europe
  "Russia": "🇷🇺",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "United Kingdom": "🇬🇧",
  "Great Britain": "🇬🇧",
  "Ireland": "🇮🇪",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "France": "🇫🇷",
  "Germany": "🇩🇪",
  "Spain": "🇪🇸",
  "Italy": "🇮🇹",
  "Portugal": "🇵🇹",
  "Netherlands": "🇳🇱",
  "Poland": "🇵🇱",
  "Sweden": "🇸🇪",
  "Norway": "🇳🇴",
  "Denmark": "🇩🇰",
  "Finland": "🇫🇮",
  "Czech Republic": "🇨🇿",
  "Slovakia": "🇸🇰",
  "Serbia": "🇷🇸",
  "Croatia": "🇭🇷",
  "Ukraine": "🇺🇦",
  "Georgia": "🇬🇪",
  "Romania": "🇷🇴",
  "Bulgaria": "🇧🇬",
  "Hungary": "🇭🇺",
  "Austria": "🇦🇹",
  "Switzerland": "🇨🇭",
  "Belgium": "🇧🇪",
  "Greece": "🇬🇷",
  // Asia & Central Asia
  "Kazakhstan": "🇰🇿",
  "Uzbekistan": "🇺🇿",
  "Kyrgyzstan": "🇰🇬",
  "Tajikistan": "🇹🇯",
  "Turkmenistan": "🇹🇲",
  "Azerbaijan": "🇦🇿",
  "Armenia": "🇦🇲",
  "Mongolia": "🇲🇳",
  "China": "🇨🇳",
  "Japan": "🇯🇵",
  "South Korea": "🇰🇷",
  "Korea": "🇰🇷",
  "Philippines": "🇵🇭",
  "Thailand": "🇹🇭",
  "Indonesia": "🇮🇩",
  "Malaysia": "🇲🇾",
  "Singapore": "🇸🇬",
  "Vietnam": "🇻🇳",
  "Myanmar": "🇲🇲",
  "Cambodia": "🇰🇭",
  "India": "🇮🇳",
  "Pakistan": "🇵🇰",
  "Bangladesh": "🇧🇩",
  "Sri Lanka": "🇱🇰",
  "Nepal": "🇳🇵",
  "Bahrain": "🇧🇭",
  "Iran": "🇮🇷",
  "Iraq": "🇮🇶",
  "Saudi Arabia": "🇸🇦",
  "UAE": "🇦🇪",
  "United Arab Emirates": "🇦🇪",
  "Turkey": "🇹🇷",
  "Israel": "🇮🇱",
  // Africa & Oceania
  "Nigeria": "🇳🇬",
  "Ghana": "🇬🇭",
  "Senegal": "🇸🇳",
  "Cameroon": "🇨🇲",
  "Morocco": "🇲🇦",
  "Egypt": "🇪🇬",
  "South Africa": "🇿🇦",
  "Kenya": "🇰🇪",
  "Australia": "🇦🇺",
  "New Zealand": "🇳🇿",
};

export function getFlagEmoji(nationality: string | null | undefined): string {
  if (!nationality) return "";
  return FLAG_MAP[nationality] ?? "";
}

/**
 * Versão "always returns something": se nacionalidade não for conhecida, retorna 🌐.
 * Use em listagens onde queremos sempre um indicador visual ao lado do nome.
 */
export function getFlagEmojiOrFallback(nationality: string | null | undefined): string {
  return getFlagEmoji(nationality) || "🌐";
}
